### ISSUE TITLE
Error al instalar sistema base en virtualbox

### ISSUE THREAD

**Issue by MrArdillo** [CambonOS/Installer#42]
![imagen](https://user-images.githubusercontent.com/77178902/192328925-db8af5fd-174b-4c86-b629-b5cfed98debc.png)
Probado con conexión NAT y puente en tres máquinas virtuales diferentes y dan todas el mismo error

**Comment by CambonOS** [comment]
Buenos dias MrArdillo,

Intentaremos reproducir el error en la mayor brebedad posible y encontrar una solucion, gracias por notificarnoslo.

Puedes indicarnos que archivo .iso estas utilizando concretamente, gracias nuevamente.

Un saludo.
Soporte CambonOS

**Comment by MrArdillo** [comment]
Uso la iso 2022.08.07

**Comment by CambonOS** [comment]
Buenas tardes MrArdillo,

Tras realizar varias pruebas tanto en maquinas virtuales como en equipos físicos no logramos reproducir el error.
Inténtalo con la nueva ISO que se a subido que ademas incluye un nuevo comando.

Un saludo.
Soporte CambonOS

**Comment by MrArdillo** [comment]
Con la nueva iso vuelve a funcionar perfectamente
